(defun main ()
  (let ((vnot 0.0)
        (g 0.0)
        (t 0.0)
        (theta 0.0)
        (vx 0.0)
        (vy 0.0))
    (format t "Enter value for vnot: ")
    (setf vnot (read))
    (format t "Enter value for g: ")
    (setf g (read))
    (format t "Enter value for theta (in degrees): ")
    (setf theta (read))
    (setf theta (* theta (pi) 180))
    (setf x-max (* 2 (expt vnot 2) g (sin theta) (cos theta)))
    (setf y-max (/ (expt vnot 2) (* 2 g) (expt (sin theta) 2)))
    (format t "Enter value for t: ")
    (setf t (read))
    (setf x (* vnot t (cos theta)))
    (setf y (- (* vnot t (sin theta)) (* 0.5 g (expt t 2))))
    (setf t-x-max (* 2 vnot g (sin theta)))
    (setf vx (* vnot (cos theta)))
    (setf vy (- (* vnot (sin theta)) (* g t)))
    (setf v (sqrt (+ (expt vx 2) (expt vy 2))))
    (setf theta (atan vx vy))
    (setf theta (* theta 180 (pi)))
    (format t "Xmax = ~f~%" x-max)
    (format t "Ymax = ~f~%" y-max)
    (format t "X = ~f~%" x)
    (format t "Y = ~f~%" y)
    (format t "Txmax = ~f~%" t-x-max)
    (format t "V = ~f~%" v)
    (format t "Theta = ~f degrees~%" theta)))
